Add button to search alerts near source on source page
fritz-marshal/fritz pull request #295
Opened 2021-06-04 22:24 UTC by acrellin

This PR introduces a button to the source page that, when clicked, submits a request to query alerts within 3 arcseconds of the source in question and redirects to the alerts page to render the results. Other improvements to the alerts page, including a spinner during request processing, and redux state structure updates, are included.

Partially addresses https://github.com/fritz-marshal/fritz/issues/287

![alerts_search_button](https://user-images.githubusercontent.com/7230285/120868269-87b47580-c548-11eb-8c45-939efedd6194.gif)

2021-06-07 19:29 UTC, acrellin commented
CI failure unrelated

2021-06-16 22:17 UTC, kmshin1397 requested changes
Looks good other than some renaming, thanks @acrellin!

2021-06-16 22:17 UTC, kmshin1397 commented on extensions/skyportal/static/js/components/ArchiveSearchButton.jsx
> +const AlertsSearchButton = ({ ra, dec, radius = 3 }) => {
```suggestion
const ArchiveSearchButton = ({ ra, dec, radius = 3 }) => {
```

2021-06-16 22:17 UTC, kmshin1397 commented on extensions/skyportal/static/js/components/ArchiveSearchButton.jsx
> +AlertsSearchButton.propTypes = {
```suggestion
ArchiveSearchButton.propTypes = {
```

2021-06-16 22:17 UTC, kmshin1397 commented on extensions/skyportal/static/js/components/ArchiveSearchButton.jsx
> +AlertsSearchButton.defaultProps = {
```suggestion
ArchiveSearchButton.defaultProps = {
```

2021-06-16 22:17 UTC, kmshin1397 commented on extensions/skyportal/static/js/components/ArchiveSearchButton.jsx
> +export default AlertsSearchButton;
```suggestion
export default ArchiveSearchButton;
```

2021-06-16 22:23 UTC, acrellin commented
@kmshin1397 ah right, of course. Fixed!

2021-06-16 22:31 UTC, kmshin1397 approved these changes

2021-06-26 06:47 UTC, dmitryduev requested changes
Looks great, thanks @acrellin! A few requests:

Could you please: 
- Make the buttons the same size (i.e. smaller) as the ones below? 
- Move them up so that they appear right after the coordinates (since we'll be querying by coordinates)?
- Unrelated to this PR, but I'd swap redshift and TNS match info in the header - the latter is also done by coordinates, so would be more natural to appear after the buttons from this PR.
- How hard would it be to fill out the forms on the Alerts/Archive pages with the ra/dec/radius info so that the user can see what was searched?

2021-06-26 06:47 UTC, dmitryduev commented on extensions/skyportal/static/js/components/ArchiveSearchButton.jsx
> +      <Button variant="contained">View ZTF Light Curve Archive</Button>
```suggestion
      <Button variant="contained">Search ZTF Light Curve Archive</Button>
```

2021-06-26 06:47 UTC, dmitryduev commented on extensions/skyportal/static/js/components/AlertsSearchButton.jsx
> +        Search Nearby Alerts
```suggestion
        Search ZTF Alert Archive
```

2021-06-26 06:47 UTC, dmitryduev commented on extensions/skyportal/static/js/components/AlertsSearchButton.jsx
> +    dispatch(alertsActions.fetchAlerts({ object_id: objID, ra, dec, radius }));
There may be sources with other `objectId`'s within 3 arcseconds - let's not restrict the search to the current `objID` only:

```suggestion
    dispatch(alertsActions.fetchAlerts({ ra, dec, radius }));
```

2021-06-26 06:47 UTC, dmitryduev commented on extensions/skyportal/static/js/components/SourceDesktop.jsx
> +              <AlertsSearchButton objID={source.id} ra={source.ra} dec={source.dec} />
```suggestion
              <AlertsSearchButton ra={source.ra} dec={source.dec} />
```

2021-06-26 06:47 UTC, dmitryduev commented on extensions/skyportal/static/js/components/AlertsSearchButton.jsx
> +const AlertsSearchButton = ({ objID, ra, dec, radius = 3 }) => {
```suggestion
const AlertsSearchButton = ({ ra, dec, radius = 3 }) => {
```

2021-06-26 06:47 UTC, dmitryduev commented on extensions/skyportal/static/js/components/AlertsSearchButton.jsx
> +  objID: PropTypes.string.isRequired,
```suggestion
```

2021-07-01 22:09 UTC, acrellin commented
@dmitryduev I've addressed all of your comments except for the form population which would require storing the form-values-to-be in redux state and populating the component's inputs accordingly. Doesn't seem like there's much added benefit for that work (they can easily see the coords of the source from which they clicked search). Thoughts?

2021-07-01 23:11 UTC, dmitryduev approved these changes
👍🏻 
re: autofill - let's leave it for now.

2021-07-01 23:11 UTC, merged